
const image1 = 'https://www.w3schools.com/howto/img_fjords.jpg';
const image2= 'https://cdn.pixabay.com/photo/2016/06/18/17/42/image-1465348_960_720.jpg';
const image3= 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXEZRoYOhIJxL5foNz_NlatDlgYStzZgVIiKuo6vtRtz2wY-8b4Q';

export default [
    {
        id: '1',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '10$',
        size: 'S',
        status: 'new',
        location: '',
        image: image1,
    },
    {
        id: '2',
        category: 'Cloths',
        subCategory: 'Shirt',
        price: '30$',
        size: 's',
        status: 'old',
        location: '',
        image: image2,
    },
    {
        id: '3',
        category: 'Cloths',
        subCategory: 'Pants',
        price: '12$',
        size: 'L',
        status: 'new',
        location: '',
        image: image3,
    },
    {
        id: '4',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '18$',
        size: 'XL',
        status: 'very old',
        location: '',
        image: image1,
    },
    {
        id: '11',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '10$',
        size: 'S',
        status: 'new',
        location: '',
        image: image2,
    },
    {
        id: '12',
        category: 'Cloths',
        subCategory: 'Shirt',
        price: '30$',
        size: 's',
        status: 'old',
        location: '',
        image: image3,
    },
    {
        id: '13',
        category: 'Cloths',
        subCategory: 'Pants',
        price: '12$',
        size: 'L',
        status: 'new',
        location: '',
        image: image1,
    },
    {
        id: '14',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '18$',
        size: 'XL',
        status: 'very old',
        location: '',
        image: image2,
    },
    {
        id: '21',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '10$',
        size: 'S',
        status: 'new',
        location: '',
        image: image3,
    },
    {
        id: '22',
        category: 'Cloths',
        subCategory: 'Shirt',
        price: '30$',
        size: 's',
        status: 'old',
        location: '',
        image: image1,
    },
    {
        id: '23',
        category: 'Cloths',
        subCategory: 'Pants',
        price: '12$',
        size: 'L',
        status: 'new',
        location: '',
        image: image2,
    },
    {
        id: '24',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '18$',
        size: 'XL',
        status: 'very old',
        location: '',
        image: image3,
    },
]