
export default [
    {
        id: '1',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '10$',
        size: 'S',
        status: 'new',
        location: '',
        image: '',
    },
    {
        id: '2',
        category: 'Cloths',
        subCategory: 'Shirt',
        price: '30$',
        size: 's',
        status: 'old',
        location: '',
        image: '',
    },
    {
        id: '3',
        category: 'Cloths',
        subCategory: 'Pants',
        price: '12$',
        size: 'L',
        status: 'new',
        location: '',
        image: '',
    },
    {
        id: '4',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '18$',
        size: 'XL',
        status: 'very old',
        location: '',
        image: '',
    },
    {
        id: '11',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '10$',
        size: 'S',
        status: 'new',
        location: '',
        image: '',
    },
    {
        id: '12',
        category: 'Cloths',
        subCategory: 'Shirt',
        price: '30$',
        size: 's',
        status: 'old',
        location: '',
        image: '',
    },
    {
        id: '13',
        category: 'Cloths',
        subCategory: 'Pants',
        price: '12$',
        size: 'L',
        status: 'new',
        location: '',
        image: '',
    },
    {
        id: '14',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '18$',
        size: 'XL',
        status: 'very old',
        location: '',
        image: '',
    },
    {
        id: '21',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '10$',
        size: 'S',
        status: 'new',
        location: '',
        image: '',
    },
    {
        id: '22',
        category: 'Cloths',
        subCategory: 'Shirt',
        price: '30$',
        size: 's',
        status: 'old',
        location: '',
        image: '',
    },
    {
        id: '23',
        category: 'Cloths',
        subCategory: 'Pants',
        price: '12$',
        size: 'L',
        status: 'new',
        location: '',
        image: '',
    },
    {
        id: '24',
        category: 'Cloths',
        subCategory: 'Dresses',
        price: '18$',
        size: 'XL',
        status: 'very old',
        location: '',
        image: '',
    },
]